export const personalYearMeanings: Record<number, string> = {
    1: "Ano para começos, novas ideias, mudanças, reformulações e inícios em todas as áreas da sua vida. Planeje o que você deseja realizar nos próximos anos e comece a trabalhar agora; o que for iniciado neste ano terá efeito nos oito anos seguintes. Seja você mesmo e prossiga do seu próprio modo, não deixe que os outros o façam mudar de opinião. É melhor não haver uniões agora, pois a influência mais forte deste ano é a de independência e autopromoção. Você pode preparar o terreno, mas espere para completá-la num ano em que sociedades sejam mais favoráveis.",
    2: "Ano para colher o que se plantou no passado. Tempo de estudar e adquirir todo o conhecimento que possa ajudá-lo a desenvolver e melhorar seus planos. Permaneça com atitudes responsáveis. Relacionamentos e sociedades têm especial destaque e é um bom período para isso, com cautela. Construa amizades e mantenha harmonia com todos. Proceda calmamente no caminho que escolheu e contente-se em esperar por resultados mais adiante.",
    3: "É um ano bom para mostrar sua personalidade, ano de brilhar. Período para amigos e para fazer o que você gosta; divirta-se o quanto puder e aceite os convites para festas que lhe forem feitos. Seja ativo, mas sem excessos, mantenha sempre o equilíbrio. É uma boa época para férias ou pequenos descansos. Bom ano para conquistar um amor e magnetizar as pessoas, portanto cuide da aparência.",
    4: "Ano para ser produtivo e organizado. Coloque tudo em ordem e verifique os detalhes, faça da autodisciplina uma regra e evite todas as tendências para a ociosidade ou preguiça. É época desfavorável para viagens, para reformulação de relacionamentos e para divertimento. Lembre-se: você está construindo para o futuro e, se quer ter sucesso, deve assegurar-se de que tudo seja bem estruturado; corrija qualquer erro do passado e faça uma revisão completa de seus planos.",
    5: "Este é um ano cheio de imprevistos para o bom e para o mau sentido. Aquilo que foi estabelecido em bases frágeis no passado poderá ruir; situações estagnadas poderão sofrer mudanças inesperadas. Tente receber os eventos inesperados da melhor maneira para poder transformá-los de modo favorável. Considere fazer mudanças em você mesmo, nos seus negócios, no seu lar, no seu estilo de vida. Mantenha sua mente e corpo ativos. Não se torne impulsivo e impaciente, canalize suas energias para bons usos.",
    6: "Ano em que a família e o lar são muito importantes. Bom para relacionamentos, contatos e contratos. Aceite os fatos como eles acontecem, estabelecendo ritmo e harmonia em sua vida. Evite precipitação e correrias. Ajuste as diferenças, resolva os problemas, aconselhe, guie e dê assistência às pessoas quando preciso. Chance de estabilização econômica.",
    7: "Ano para a reflexão, desenvolvimento e preparação do “eu interior”. Planeje passar algum tempo sozinho e use-o construtivamente. Não viva a vida intensamente neste ano; trabalhar demais também pode ser prejudicial. A influência é espiritual, de profunda introspecção e procura.",
    8: "Ano para as economias, para o dinheiro e para os bens materiais. Através de esforço e empenho você pode realizar grandes coisas e conhecer o sucesso; além disso, poderá colher os frutos do seu trabalho ao longo dos sete anos anteriores. Aja com otimismo, prudência e com afinco para alcançar o resultado almejado.",
    9: "Tempo de iniciar a preparação para um novo ciclo e para buscar soluções dos problemas pendentes. Resolva tudo este ano, que é ano para esclarecimentos, fim de ciclo. Procure permanecer em equilíbrio e tenha praticidade. Faça uma avaliação da sua vida e elimine tudo o que considerar inútil.",
};

export const challengeMeanings: Record<number, string> = {
    0: "Aqui há dualidade: enfrentar todos os desafios indicados por todos os números ou a ausência de desafio.",
    1: "Aprenda a desenvolver com muita força de vontade, energia de caráter e coragem, ou estará sujeito a ser governado e mantido à sombra dos demais.",
    2: "Desenvolva confiança em si; faça uso dos seus talentos; não seja falso e nem evite a verdade só por querer harmonia.",
    3: "Evite dispensar seus talentos; aprenda a lidar com as críticas; aprenda a não ser extravagante e a não perder tempo, dinheiro ou palavras; não se deixe envolver pela fofoca e pela melancolia.",
    4: "Aprenda a ser disciplinado, pontual, sistemático; evite a preguiça e a teimosia.",
    5: "Tome cuidado com a impulsividade; cultive a mudança sábia; aprenda a ter discernimento com relação ao que deve ser descartado.",
    6: "Cuidado para não se tornar dominador e intrometido; não tente mudar o outro, mude a si; aprenda que todos possuem direitos às suas próprias ideias e princípios.",
    7: "Evite a melancolia; não esconda seus sentimentos; cuidado com o excesso de orgulho.",
    8: "Cuidado com o medo da carência, de perdas e suas limitações; não seja avarento.",
    9: "Cuidado com o apego ao passado, com a arrogância de achar que sabe tudo."
};

export const karmicLessonMeanings: Record<number, string> = {
    1: "Necessita estimular em si mesmo as qualidades de mundo, valor e ousadia. É muito importante que aprenda a tomar decisões e a controlar qualquer situação que requeira esforço. Necessita afirmar sua individualidade a fim de que seja ouvido e notado. Tem de aprender a ser o primeiro e o melhor em alguma coisa e, também, a caminhar em situações novas e não experimentadas.",
    2: "Deve aprender a arte sutil da cooperação, do tato e da diplomacia. Trabalhar em associação com outros requer colocar algo da sua parte. Aprenda a permanecer em segundo plano, em caso necessário.",
    3: "Deve desenvolver a autoexpressão. Estimule seus talentos comunicativos desenvolvendo a arte da palavra. Terá de adotar um ponto de vista feliz e otimista e espalhar entusiasmo e alegria por onde quer que vá.",
    4: "Deve adotar um modo de vida ordenado, sistemático, que lhe permita uma existência estruturada. Aplique suas energias em um objetivo tangível, mediante trabalho sistemático e disciplinado. Cuide de suas finanças.",
    5: "Precisa aprender a ajustar-se às mudanças e a ser mais versátil. Deve estimular seu sentido de liberdade física, mental e espiritual. Precisa viajar e relacionar-se com diversos tipos de pessoas.",
    6: "Deve expressar mais amor pelos seus semelhantes. O 6 é uma vibração de lugar, e a sua ausência indica a necessidade de aprofundar os laços de afeto com aqueles que formam sua família imediata e seu meio ambiente. Desenvolva um sentido de responsabilidade social.",
    7: "Deve desenvolver sua mente e sua parte intuitiva e filosófica. Abandone de vez em quando o mundo material e aprenda a penetrar em si mesmo, a meditar e a ponderar o conteúdo de seu próprio ser.",
    8: "Convém a você canalizar suas energias no mundo material, com o objetivo de alcançar uma posição de liderança. Desenvolva seus sentidos de negócios. Terá de representar o papel de “chefe”.",
    9: "Deve converter-se no universalista, na pessoa humanitária cuja preocupação principal consiste no bem-estar dos demais. Deve desenvolver sua amplitude de pensamentos e um amor universal pelos seus semelhantes."
};

export const hiddenTendencyMeanings: Record<number, string> = {
    1: "Desejo da individualidade. Há uma tendência a ser autoritário, dominador, arrogante e um tanto egoísta.",
    2: "Desejo de associações. Há uma tendência para depender demasiado dos outros, principalmente da família e dos amigos.",
    3: "Desejo da autoexpressão. Há uma tendência à vaidade, à impaciência, à presunção, a dispersar energias, viver sem objetivos concretos.",
    4: "Desejo de trabalho. Há uma tendência para asfixiar sua personalidade com quantidade excessiva de detalhes (perfeccionista), de ser teimoso, intolerante e obstinado.",
    5: "Desejo de mudança e também de liberdade pessoal. Há uma tendência para ser precipitado e impulsivo, e mudanças sem motivo aparente.",
    6: "Desejo de realização e responsabilidade. Há uma tendência para se preocupar excessivamente com a família, para ser teimoso, perfeccionista e para apegar-se a modelos inflexíveis.",
    7: "Desejo de sabedoria e conhecimento. Há uma tendência para o fingimento, para a intriga e até para o isolamento, pois normalmente se sente incompreendido.",
    8: "Desejo do materialismo. Há uma tendência para se preocupar excessivamente em como ganhar dinheiro, obter bens materiais e também poder.",
    9: "Desejo de conhecimento e amor universal. Há uma tendência para se preocupar excessivamente com os problemas mundiais em detrimento de si mesmo e da família."
};

export const missionMeanings: Record<number, string> = {
    1: "Ativo, corajoso, voluntarioso, determinado e seguro. Está direcionado para um objetivo único: VENCER. Esta palavra significa para você: afirmar-se, exprimir sua alma de chefe, dirigir uma equipe e propagar as suas ideias. Exigente, autoritário, você não espera dos outros presentes que você não estaria disposto a dar lhes. É generoso e apaixonado, um amante instigante, exclusivo e indomável.",
    2: "Sonhador e sensível, você é diplomata, imaginativo e equilibrado. Tendência para a passividade e a preguiça. Se você fizesse o que quisesse, passaria o dia vagabundeando. É por isso que os outros lhe são tão necessários, eles estimulam você, aguçam seus anseios e canalizam sua energia. Você tem necessidade de uma equipe estável para se realizar e se desenvolver, como também de uma atmosfera serena e de um equilíbrio afetivo. Quando dotado para o comércio, você tem o dom de levar as negociações a bom termo. Você sabe se mostrar criativo. Doce e sonhador, o casamento é para você mais um refúgio do que um fim de si mesmo.",
    5: "Criativo, aventureiro, você é brilhante, vivo e dinâmico. As suas características de curiosidade e de adaptação e, a sua necessidade de manter contatos são os melhores atributos do seu sucesso material. Empreendedor e alegre, você ama o movimento, a aventura, mas com certo conforto. As experiências novas o seduzem, as pessoas originais o entusiasmam e você se apaixona por ideias generosas. Tudo isso faria de você um retrato superficial se não houvesse sua vida sentimental. Nesse campo, após os namoricos, você saberá usar a medida certa, inteira, leal e apaixonada.",
    6: "Responsável, perfeccionista, você é cuidadoso, meticuloso, sensível e sério. A todas essas qualidades vem se juntar uma outra: o senso artístico. Intuitivo também, você sabe dirigir sua carreira graças à diplomacia e ao senso de relações humanas. Entretanto, pode faltar-lhe rigor e determinação, pois você tende a se deixar levar pela facilidade. Outro ponto fraco: tendência para a luxúria. No amor, você quer agradar e procura a felicidade numa vida sentimental equilibrada. A atividade no lar pode mesmo dominar. O número 6 atravessa períodos de sensualidade transbordante.",
    7: "Independente, meditativo, original. Você é um inovador, forte, antes para criar do que para viver uma realidade rotineira. Os hábitos e os lugares comuns o entediam. Aliás, você foge deles. O seu espírito analítico vai bem de acordo com o seu gosto pelo estudo. Você tem desejo de progredir sem cessar. Você tem o culto pela amizade, o que não exclui os acessos de pessimismo quando a solidão lhe pesa. Muito exigente e criativo tanto no amor, como em outras coisas, você deseja uma relação durável, baseada na igualdade de interesses e gostos. Preferencialmente um parceiro intelectual, com a condição de não se tornar tedioso, nem triste.",
    8: "Combatente, você é energético, corajoso, empreendedor. Como você tem o senso do concreto, das ideias originais e brilhante e, o gosto pelo sucesso, você atuará mais por trancos do que seguindo uma trajetória lenta. Preciso, organizado, você sabe tecer ao seu redor uma rede de relações extremamente eficaz, mostrando se leal e determinado. Em compensação, você parece duro em relação aos seus adversários e traidores. No amor você é exigente, ciumento, impetuoso. Você é mais dominante do que dominado. O desejo de agradar não contradiz a sua necessidade de uma união estável e durável, mesmo que isso seja para afirmar sua imagem.",
    9: "Idealista, humanitário, intuitivo, secreto e sonhador. Todo mundo apreciará a sua imaterialidade, as suas ideias generosas, o seu altruísmo. As suas palavras pegam a partilha, a disponibilidade e a compreensão. Pode haver a tendência para a desordem, para o contraditório e manifestar um sentido de credulidade exagerado. Muitas vezes é influenciável, você não conseguirá trabalhar eficientemente se não sentir-se motivado e acreditar naquilo que está fazendo. Um clima de confiança é necessário para mantê-lo em forma. No amor você tem necessidade de ser amparado e pede constantemente provas de amor e lealdade, o que pode se tornar cansativo. Mas é fiel, leal e o outro perdoará sua falta de senso prático, porque você tem alguma coisa rara: O SONHO.",
    11: "Visionário com oportunidade de servir a humanidade, atrai adeptos e publicidade para os ideais pessoais exclusivos. Místico, vanguardista e evangelizador, o 11 atrai fama quando despojado. Toma decisões constantemente detonadas por uma energia nervosa e muito sensível. Vez ou outra, abranda e repousa como um receptivo 2, mas quando está desequilibrado é desafiado pelo próprio número 2. Líder carismático para verdades universais. Consegue transmitir inspiração aos outros. Senso inato de equilíbrio. Unifica propósitos, consegue solucionar conflitos. Criativo e inventivo atrai a publicidade 'dourada' e a liderança entre as elites. Os talentos conduzem a ensinar, inventar, filosofar, interpretar, fazer programas de computador, escrever ou interesses metafísicos e espirituais. Deve seguir os ideais pessoais, dar o exemplo, e querer ser diferente para viver segundo as possibilidades mestras do número 11.",
    22: "São construtores mestres que têm uma ideia, planejam os detalhes e trabalham no sentido de atingir os resultados concretos. Tem um potencial extraordinário para conquistar riqueza e influência. Instigados no nível mental, físico e espiritual, gostam de conversar sobre tendências. A inspiração que recebe tem raiz em sua intuição muitíssimo desenvolvida. Influente e educado, procuro o máximo alcançar o mercado mundial. Autoritário, criativo e intenso quando está envolvido na organização de grandes reformas. Quando atuam sob a energia do 4, as pressões do 22 são reduzidas, e é pouco provável que as suas realizações tenham influência tão benéfica ou que atinjam um amplo horizonte de operações. Uma pessoa sob essa influência tem aptidão para toda e qualquer coisa que seja para o bem de todos. É um administrador magistral e tem vocação para os negócios. Luta pela melhoria da humanidade. Tem habilidade para transformar sonhos em realidade."
};
